# configs/default.yml — OCR settings override (optional)

supported_extensions:
  - ".jp2"
  - ".tif"
  - ".tiff"
  - ".png"

batch_size: 4
api_rate_limit_delay: 0.0

enable_deskewing: true
max_skew_angle: 6.0
skew_threshold: 0.4

min_confidence: 0.0

preprocessing_params:
  default:
    clahe: true
    blur: true
    blur_kernel: [3, 3]
    sauvola_window: 35
    sauvola_k: 0.2
    closing: true
    closing_kernel_size: [2, 2]

min_text_density: 0.05
max_text_density: 0.35
min_headline_area: 20000
max_headline_area: 300000
min_body_area: 2000
min_ad_area: 120000

metadata_patterns:
  date: "\\b(\\d{4}-\\d{2}-\\d{2})\\b"
  page: "page\\s+(\\d+)"

# Optional Google Cloud credentials
# credentials_path: /path/to/your/service_account.json
